version = '0.0.0'

[[files."CHANGELOG.md"]]
search = """
## [Unreleased] ##
"""
replace = """
## [Unreleased] ##

## [{{new_version}}] - {{utcnow | strftime('%Y-%m-%d')}} ##
"""

[[files."CHANGELOG.md"]]
search = """
[Unreleased]: https://github.com/dochang/ansible-role-opensshserver/compare/{{old_version}}...HEAD
"""
replace = """
[Unreleased]: https://github.com/dochang/ansible-role-opensshserver/compare/{{new_version}}...HEAD
[{{new_version}}]: https://github.com/dochang/ansible-role-opensshserver/compare/{{old_version}}...{{new_version}}
"""

[[files."CHANGELOG.md"]]
search = """
[Unreleased]: https://github.com/dochang/ansible-role-opensshserver/commits/HEAD
"""
replace = """
[Unreleased]: https://github.com/dochang/ansible-role-opensshserver/compare/{{new_version}}...HEAD
[{{new_version}}]: https://github.com/dochang/ansible-role-opensshserver/commits/{{new_version}}
"""
