---
- name: configure openssh server
  lineinfile:
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '644'
    backup: yes
    create: yes
    validate: 'sshd -t -f %s'
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
    state: present
  with_items:
    - regexp: '(?i)^[\s#]*PermitRootLogin\s+(.*)$'
      line: 'PermitRootLogin {{ opensshserver_permitrootlogin }}'
    - regexp: '(?i)^[\s#]*PermitEmptyPasswords\s+(.*)$'
      line: 'PermitEmptyPasswords {{ opensshserver_permitemptypasswords }}'
    - regexp: '(?i)^[\s#]*PasswordAuthentication\s+(.*)$'
      line: 'PasswordAuthentication {{ opensshserver_passwordauthentication }}'
    - regexp: '(?i)^[\s#]*GSSAPIAuthentication\s+(.*)$'
      line: 'GSSAPIAuthentication {{ opensshserver_gssapiauthentication }}'
    - regexp: '(?i)^[\s#]*PubkeyAuthentication\s+(.*)$'
      line: 'PubkeyAuthentication {{ opensshserver_pubkeyauthentication }}'
  notify: restart openssh server

- meta: flush_handlers
