---
- name: include os specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - default.yml
      paths:
        # `../vars/` is required because `with_first_found` looks in the
        # `files/` directory.  See Ansible issues [7788][], [5108][] and this
        # [page][] for details:
        #
        # [7788]: https://github.com/ansible/ansible/issues/7788
        # [5108]: https://github.com/ansible/ansible/issues/5108
        # [page]: https://groups.google.com/forum/#!topic/ansible-project/UQ_ArPEofFU
        - ../vars/installer

- include: install.yml

- name: configure openssh server
  lineinfile:
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '644'
    backup: yes
    create: yes
    validate: 'sshd -t -f %s'
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
    state: present
  with_items:
    - regexp: '(?i)^\s*permitrootlogin\s+(.*)$'
      line: 'permitrootlogin {{ opensshserver_permitrootlogin }}'
    - regexp: '(?i)^\s*permitemptypasswords\s+(.*)$'
      line: 'permitemptypasswords {{ opensshserver_permitemptypasswords }}'
    - regexp: '(?i)^\s*passwordauthentication\s+(.*)$'
      line: 'passwordauthentication {{ opensshserver_passwordauthentication }}'
    - regexp: '(?i)^\s*gssapiauthentication\s+(.*)$'
      line: 'gssapiauthentication {{ opensshserver_gssapiauthentication }}'
    - regexp: '(?i)^\s*pubkeyauthentication\s+(.*)$'
      line: 'pubkeyauthentication {{ opensshserver_pubkeyauthentication }}'
  notify: restart openssh server

- meta: flush_handlers
